NAME: 'swinTrans.b_24_large_csra8_0.3_pooling2fpn.adam'

PIPELINE: 'Swin_FPN_ALM'


DATASET:
  TYPE: 'PAR'
  NAME: 'PAReg'
  TRAIN_SPLIT: 'train'
  VAL_SPLIT: 'val'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 192

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  # TYPE: 'resnet50'
#  TYPE: 'bninception'
#  TYPE: 'tresnetM'
 # TYPE: 'swin_s'
 # TYPE: 'swin_l_384'
 TYPE: 'swin_l_fpn'


#  TYPE: 'vit_s'
#  TYPE: 'vit_b'

CLASSIFIER:
  NAME: 'csra'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'fpn_bceloss'
  LOSS_WEIGHT: [1,1,1,1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 16
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.00001
    LR_NEW: 0.0001
  EMA:
    ENABLE: False
  MAX_EPOCH: 30

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
