NAME: 'resnet101.EMA.adam'

DATASET:
  TYPE: 'VAR'
  NAME: 'VAReg'
  TRAIN_SPLIT: 'train'
  VAL_SPLIT: 'val'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 448
  WIDTH: 448

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  # TYPE: 'resnet50'
  TYPE: 'resnet101'
#  TYPE: 'bninception'
#  TYPE: 'tresnetM'
 # TYPE: 'swin_s'
#  TYPE: 'vit_s'
#  TYPE: 'vit_b'

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 16
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.0001
    LR_NEW: 0.0001
  EMA:
    ENABLE: True
  MAX_EPOCH: 80

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
